apiVersion: v1
kind: Secret
metadata:
    name: mailer-backend-secret
    namespace: mailer
    labels:
      app: mailer-backend
type: Opaque
data:
    # this is just a template, should not be used for prod
    # base 64 encoded
    AWS_ACCESS_KEY: QUtJQVZOMkVDTFZGREdUWEI1RDU=
    AWS_SECRET_ACCESS_KEY: aWxaMHdmUmp6UmVIbGdUbEkvV05GYktPR0xOMytFY0pnQk4yNjZLUg==
    EMAIL_ADDRESS: bWVsdmluLmxpZXcua29rLmxlb25nQGdtYWlsLmNvbQ==
    CLIENT_ID: NDYzMDQ4ODc3OTItYm0yMHNqY2Y0aG5pcThnbWt2OGtzcWI0cXR0bWgwZDAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
    CLIENT_SECRET: R09DU1BYLVBOT0RuWjdCRGV3MXRjcVBpSGhLaVNGX0ZVTXE=
    REFRESH_TOKEN: MS8vMDRuYkZpT29LN2lzZkNnWUlBUkFBR0FRU053Ri1MOUlyelR0OTZGZHNEN2dIZVE2VXlrbDlUcTNXNDhqSGJWcWxXcjd6YTNENkw0djVQcGtWOVZuQUhpaElOT0pRaTRsVFZiWQ==
