apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: mailer-backend-hpa 
  namespace: mailer
  labels:
    app: mailer-backend
spec: 
  maxReplicas: 10 
  minReplicas: 2 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: mailer-backend-deployment 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50